-- Database: railway

-- DROP DATABASE IF EXISTS railway;

CREATE DATABASE railway
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.utf8'
    LC_CTYPE = 'en_US.utf8'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
	
CREATE TABLE ROLES (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION TEXT
);
CREATE TABLE PERMISOS (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT
);

CREATE TABLE ROL_PERMISOS (
    ID SERIAL PRIMARY KEY,
    ROL_ID INT REFERENCES ROLES(ID),
    PERMISO_ID INT REFERENCES PERMISOS(ID)
);

CREATE TABLE USUARIOS (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ROL_ID INT REFERENCES ROLES(ID),
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SUCURSALES (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DIRECCION TEXT NOT NULL
);

CREATE TABLE CATEGORIAS (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT
);

CREATE TABLE PRODUCTOS (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,
    PRECIO DECIMAL(10, 2) NOT NULL,
    TALLA VARCHAR(50),
    TIPO_PRENDA VARCHAR(50),
    COLOR VARCHAR(50),
    MEDIDAS VARCHAR(100),
    CATEGORIA_ID INT REFERENCES CATEGORIAS(ID),
    STOCK INT NOT NULL,
    SUCURSAL_ID INT REFERENCES SUCURSALES(ID)
);

CREATE TABLE IMAGENES_PRODUCTOS (
    ID SERIAL PRIMARY KEY,
    PRODUCTO_ID INT REFERENCES PRODUCTOS(ID),
    URL_IMAGEN TEXT NOT NULL
);

CREATE TABLE CARRITO_COMPRAS (
    ID SERIAL PRIMARY KEY,
    USUARIO_ID INT REFERENCES USUARIOS(ID),
    TOTAL DECIMAL(10, 2) NOT NULL,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CARRITO_ITEMS (
    ID SERIAL PRIMARY KEY,
    CARRITO_ID INT REFERENCES CARRITO_COMPRAS(ID),
    PRODUCTO_ID INT REFERENCES PRODUCTOS(ID),
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10, 2) NOT NULL
);

CREATE TABLE PEDIDOS (
    ID SERIAL PRIMARY KEY,
    USUARIO_ID INT REFERENCES USUARIOS(ID),
    TOTAL DECIMAL(10, 2) NOT NULL,
    ESTADO VARCHAR(50) NOT NULL,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PEDIDO_ITEMS (
    ID SERIAL PRIMARY KEY,
    PEDIDO_ID INT REFERENCES PEDIDOS(ID),
    PRODUCTO_ID INT REFERENCES PRODUCTOS(ID),
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10, 2) NOT NULL
);

CREATE TABLE PAGOS (
    ID SERIAL PRIMARY KEY,
    PEDIDO_ID INT REFERENCES PEDIDOS(ID),
    METODO_PAGO VARCHAR(50) NOT NULL,
    MONTO DECIMAL(10, 2) NOT NULL,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE RESERVAS (
    ID SERIAL PRIMARY KEY,
    USUARIO_ID INT REFERENCES USUARIOS(ID),
    PRODUCTO_ID INT REFERENCES PRODUCTOS(ID),
    FECHA_RESERVA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_LIMITE TIMESTAMP,
    ESTADO VARCHAR(50) NOT NULL
);

CREATE TABLE VESTIDORES_VIRTUALES (
    ID SERIAL PRIMARY KEY,
    USUARIO_ID INT REFERENCES USUARIOS(ID),
    PRODUCTO_ID INT REFERENCES PRODUCTOS(ID),
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE REPORTES (
    ID SERIAL PRIMARY KEY,
    TIPO_REPORTE VARCHAR(50) NOT NULL,
    DESCRIPCION TEXT,
    FECHA_GENERACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO ROLES (NOMBRE, DESCRIPCION) 
VALUES ('Administrador', 'Usuario con privilegios completos para gestionar el sistema.');

INSERT INTO ROLES (NOMBRE, DESCRIPCION) 
VALUES ('Cliente', 'Usuario que puede realizar compras y reservas en la tienda.');

INSERT INTO ROLES (NOMBRE, DESCRIPCION) 
VALUES ('Repartidor', 'Usuario encargado de la entrega de productos a los clientes.');

-- Insertar usuario Administrador
INSERT INTO USUARIOS (NOMBRE, EMAIL, PASSWORD_HASH, ROL_ID) 
VALUES ('Jorge Aliaga', 'jorge.aliaga@example.com', 'hashed_password_admin', 1);

-- Insertar usuario Cliente
INSERT INTO USUARIOS (NOMBRE, EMAIL, PASSWORD_HASH, ROL_ID) 
VALUES ('Maria Perez', 'maria.perez@example.com', 'hashed_password_cliente', 2);

-- Insertar usuario Repartidor
INSERT INTO USUARIOS (NOMBRE, EMAIL, PASSWORD_HASH, ROL_ID) 
VALUES ('Carlos Lopez', 'carlos.lopez@example.com', 'hashed_password_repartidor', 3);

CREATE TABLE INVENTARIO (
    ID SERIAL PRIMARY KEY,
    PRODUCTO_ID INT REFERENCES PRODUCTOS(ID),
    SUCURSAL_ID INT REFERENCES SUCURSALES(ID),
    CANTIDAD_DISPONIBLE INT NOT NULL,
    FECHA_ULTIMA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MOVIMIENTOS_INVENTARIO (
    ID SERIAL PRIMARY KEY,
    INVENTARIO_ID INT REFERENCES INVENTARIO(ID),
    TIPO_MOVIMIENTO VARCHAR(50) NOT NULL, -- Ej: 'Entrada', 'Salida'
    CANTIDAD INT NOT NULL,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DESCRIPCION TEXT
);

INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION) 
VALUES ('Vestidos', 'Ropa femenina para eventos y ocasiones especiales.');

INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION) 
VALUES ('Blusas', 'Blusas de diferentes estilos y materiales para mujeres.');

INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION) 
VALUES ('Faldas', 'Faldas de diferentes longitudes y diseños.');

INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION) 
VALUES ('Pantalones', 'Pantalones femeninos para uso casual o formal.');

INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION) 
VALUES ('Zapatos', 'Zapatos y sandalias para diversas ocasiones.');

INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION) 
VALUES ('Abrigos', 'Abrigos y chaquetas para el clima frío.');

INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION) 
VALUES ('Accesorios', 'Accesorios femeninos como bolsos, bufandas y joyas.');

INSERT INTO SUCURSALES (NOMBRE, DIRECCION) 
VALUES ('Sucursal Centro', 'Av. Principal #123, Centro, Ciudad X');

INSERT INTO SUCURSALES (NOMBRE, DIRECCION) 
VALUES ('Sucursal Norte', 'Calle Norte #456, Zona Norte, Ciudad X');

INSERT INTO SUCURSALES (NOMBRE, DIRECCION) 
VALUES ('Sucursal Sur', 'Av. Sur #789, Zona Sur, Ciudad X');

INSERT INTO SUCURSALES (NOMBRE, DIRECCION) 
VALUES ('Sucursal Este', 'Calle Este #101, Zona Este, Ciudad X');

INSERT INTO SUCURSALES (NOMBRE, DIRECCION) 
VALUES ('Sucursal Oeste', 'Av. Oeste #202, Zona Oeste, Ciudad X');


-- Vestido rojo talla M
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, TALLA, TIPO_PRENDA, COLOR, MEDIDAS, CATEGORIA_ID, STOCK, SUCURSAL_ID) 
VALUES ('Vestido Rojo', 'Vestido elegante rojo talla M', 150.00, 'M', 'Vestido', 'Rojo', '90x60x90', 1, 50, 1);

-- Blusa blanca talla S
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, TALLA, TIPO_PRENDA, COLOR, MEDIDAS, CATEGORIA_ID, STOCK, SUCURSAL_ID) 
VALUES ('Blusa Blanca', 'Blusa casual blanca talla S', 80.00, 'S', 'Blusa', 'Blanco', '85x60x85', 2, 100, 2);

-- Falda negra talla L
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, TALLA, TIPO_PRENDA, COLOR, MEDIDAS, CATEGORIA_ID, STOCK, SUCURSAL_ID) 
VALUES ('Falda Negra', 'Falda negra clásica talla L', 120.00, 'L', 'Falda', 'Negro', '95x70x95', 3, 70, 3);

-- Zapatos de tacón negro talla 38
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, TALLA, TIPO_PRENDA, COLOR, MEDIDAS, CATEGORIA_ID, STOCK, SUCURSAL_ID) 
VALUES ('Zapatos de Tacón', 'Zapatos de tacón negro talla 38', 200.00, '38', 'Zapatos', 'Negro', 'Standard', 5, 40, 1);

-- Abrigo azul talla M
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, TALLA, TIPO_PRENDA, COLOR, MEDIDAS, CATEGORIA_ID, STOCK, SUCURSAL_ID) 
VALUES ('Abrigo Azul', 'Abrigo de invierno azul talla M', 250.00, 'M', 'Abrigo', 'Azul', '100x80x100', 6, 30, 4);


-- Inventario para Vestido Rojo en la Sucursal Centro
INSERT INTO INVENTARIO (PRODUCTO_ID, SUCURSAL_ID, CANTIDAD_DISPONIBLE) 
VALUES (1, 1, 50);

-- Inventario para Blusa Blanca en la Sucursal Norte
INSERT INTO INVENTARIO (PRODUCTO_ID, SUCURSAL_ID, CANTIDAD_DISPONIBLE) 
VALUES (2, 2, 100);

-- Inventario para Falda Negra en la Sucursal Sur
INSERT INTO INVENTARIO (PRODUCTO_ID, SUCURSAL_ID, CANTIDAD_DISPONIBLE) 
VALUES (3, 3, 70);

-- Inventario para Zapatos de Tacón en la Sucursal Centro
INSERT INTO INVENTARIO (PRODUCTO_ID, SUCURSAL_ID, CANTIDAD_DISPONIBLE) 
VALUES (4, 1, 40);

-- Inventario para Abrigo Azul en la Sucursal Este
INSERT INTO INVENTARIO (PRODUCTO_ID, SUCURSAL_ID, CANTIDAD_DISPONIBLE) 
VALUES (5, 4, 30);

-- Pedido realizado por el usuario con ID 2 (Cliente)
INSERT INTO PEDIDOS (USUARIO_ID, TOTAL, ESTADO)
VALUES (2, 350.00, 'Pagado');

-- Pedido realizado por el usuario con ID 2 (Cliente) para reservar un producto
INSERT INTO PEDIDOS (USUARIO_ID, TOTAL, ESTADO)
VALUES (2, 250.00, 'Reservado');

-- Pedido realizado por el usuario con ID 3 (Cliente)
INSERT INTO PEDIDOS (USUARIO_ID, TOTAL, ESTADO)
VALUES (3, 200.00, 'Pagado');
-- Items para el primer pedido (Pedido ID 1)
INSERT INTO PEDIDO_ITEMS (PEDIDO_ID, PRODUCTO_ID, CANTIDAD, PRECIO_UNITARIO)
VALUES (1, 1, 1, 150.00); -- Vestido Rojo

INSERT INTO PEDIDO_ITEMS (PEDIDO_ID, PRODUCTO_ID, CANTIDAD, PRECIO_UNITARIO)
VALUES (1, 2, 2, 100.00); -- Blusa Blanca (x2)

-- Items para el segundo pedido (Pedido ID 2, reserva de un producto)
INSERT INTO PEDIDO_ITEMS (PEDIDO_ID, PRODUCTO_ID, CANTIDAD, PRECIO_UNITARIO)
VALUES (2, 5, 1, 250.00); -- Abrigo Azul

-- Items para el tercer pedido (Pedido ID 3)
INSERT INTO PEDIDO_ITEMS (PEDIDO_ID, PRODUCTO_ID, CANTIDAD, PRECIO_UNITARIO)
VALUES (3, 4, 1, 200.00); -- Zapatos de Tacón

-- Permisos para gestionar usuarios
INSERT INTO PERMISOS (NOMBRE, DESCRIPCION) 
VALUES ('GESTIONAR_USUARIOS', 'Permiso para crear, editar y eliminar usuarios.');

-- Permisos para gestionar roles
INSERT INTO PERMISOS (NOMBRE, DESCRIPCION) 
VALUES ('GESTIONAR_ROLES', 'Permiso para crear, editar y eliminar roles.');

-- Permisos para gestionar productos
INSERT INTO PERMISOS (NOMBRE, DESCRIPCION) 
VALUES ('GESTIONAR_PRODUCTOS', 'Permiso para crear, editar y eliminar productos.');

-- Permisos para gestionar pedidos
INSERT INTO PERMISOS (NOMBRE, DESCRIPCION) 
VALUES ('GESTIONAR_PEDIDOS', 'Permiso para gestionar los pedidos de los clientes.');

-- Permisos para gestionar inventario
INSERT INTO PERMISOS (NOMBRE, DESCRIPCION) 
VALUES ('GESTIONAR_INVENTARIO', 'Permiso para gestionar el inventario de productos.');

-- Permiso para ver reportes
INSERT INTO PERMISOS (NOMBRE, DESCRIPCION) 
VALUES ('VER_REPORTES', 'Permiso para ver reportes de ventas e inventario.');

-- Permisos para el Administrador
INSERT INTO ROL_PERMISOS (ROL_ID, PERMISO_ID) VALUES (1, 1); -- GESTIONAR_USUARIOS
INSERT INTO ROL_PERMISOS (ROL_ID, PERMISO_ID) VALUES (1, 2); -- GESTIONAR_ROLES
INSERT INTO ROL_PERMISOS (ROL_ID, PERMISO_ID) VALUES (1, 3); -- GESTIONAR_PRODUCTOS
INSERT INTO ROL_PERMISOS (ROL_ID, PERMISO_ID) VALUES (1, 4); -- GESTIONAR_PEDIDOS
INSERT INTO ROL_PERMISOS (ROL_ID, PERMISO_ID) VALUES (1, 5); -- GESTIONAR_INVENTARIO
INSERT INTO ROL_PERMISOS (ROL_ID, PERMISO_ID) VALUES (1, 6); -- VER_REPORTES
-- Permisos para el Cliente
INSERT INTO ROL_PERMISOS (ROL_ID, PERMISO_ID) VALUES (2, 4); -- GESTIONAR_PEDIDOS

-- Carrito de compras para el usuario con ID 2 (Cliente)
INSERT INTO CARRITO_COMPRAS (USUARIO_ID, TOTAL)
VALUES (2, 250.00);

-- Carrito de compras para el usuario con ID 3 (Cliente)
INSERT INTO CARRITO_COMPRAS (USUARIO_ID, TOTAL)
VALUES (3, 150.00);

